name = "ews-worker"
main = "src/index.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
R2_ACCOUNT_ID = "8f89a83cd9cc730f7dd298e536eea9b2"
R2_BUCKET_NAME = "ossapac"

[triggers]
crons = ["*/1 * * * *"]

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "baseapac"
database_id = "8a323729-e862-4daf-b29d-24eb4f840715"
migrations_dir = "migrations"

# R2 存储桶绑定
[[r2_buckets]]
binding = "R2"
bucket_name = "ossapac"

[[queues.producers]]
binding = "CALLBACK_EVENTS"
queue = "ews-callback-events"

[[queues.consumers]]
queue = "ews-callback-events"
max_batch_size = 1
max_batch_timeout = 1
max_retries = 5
dead_letter_queue = "ews-callback-events-dlq"
max_concurrency = 20
